// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Upload_File_Pjt;

#nullable disable

namespace Upload_File_Pjt.Migrations
{
    [DbContext(typeof(UploadContext))]
    partial class UploadContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Upload_File_Pjt.Models.CSVUpload", b =>
                {
                    b.Property<int>("csvUploadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("csvUploadId"), 1L, 1);

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("currencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("tranDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("tranIdentificator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("csvUploadId");

                    b.ToTable("cSVUploads");
                });

            modelBuilder.Entity("Upload_File_Pjt.Models.XMLUpload", b =>
                {
                    b.Property<int>("xmlUpladId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("xmlUpladId"), 1L, 1);

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("currencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("tranDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("tranId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("xmlUpladId");

                    b.ToTable("xmlUploads");
                });
#pragma warning restore 612, 618
        }
    }
}
